### ISSUE TITLE
Helm/Cloak toggle checkboxes in Character panel also appearing in the wrong tabs (Reputation, Skills, Honor)

### ISSUE THREAD

**Issue by drixlow** [leatrix/leatrix-plus-classic#11]
With the the 1.13.103 update it appears that the Helm/Cloak visibility checkboxes in the Character panel are now appearing in the other tabs when they were not previously doing so. Seems like something broke with the introduction of the new changes to the enhance dressup option. Screenshots attached for reference.

![image](https://user-images.githubusercontent.com/83472877/116742418-54208180-a9c5-11eb-9529-4d80b06d5e29.png)
![image](https://user-images.githubusercontent.com/83472877/116742434-5c78bc80-a9c5-11eb-8eb6-242a15d241bf.png)
![image](https://user-images.githubusercontent.com/83472877/116742446-5f73ad00-a9c5-11eb-8059-3f90f0a34db2.png)
![image](https://user-images.githubusercontent.com/83472877/116742658-a9f52980-a9c5-11eb-926e-336ce2a833c6.png)

**Comment by leatrix** [comment]
Many thanks for the report.  It's fixed in 1.13.104.alpha.1.
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all
