### ISSUE TITLE
Text in stats window after May 4th update

### ISSUE THREAD

**Issue by Mirabellan** [leatrix/leatrix-plus-classic#12]
![20210505_085620](https://user-images.githubusercontent.com/83693574/117107989-d1ac0f00-ad82-11eb-9426-0b84ddd1647d.jpg)

**Comment by Mirabellan** [comment]
Installed Leatrix_Plus-1.13.103 and issue is gone, only appears in the 104.

**Comment by leatrix** [comment]
Leatrix Plus 1.13.104 adds a feature to 'Enhance dressup' ('Interface') which allows you to toggle the character attributes in the character frame by middle-clicking the character model.  You appear to be using CharacterStatsClassic (correct me if I'm wrong) which has its own character attributes panel that Leatrix Plus cannot toggle.  In 1.13.105.alpha.1, the feature to toggle the character attributes is disabled if you have CharacterStatsClassic installed.  There's no need to disable 'Enhance dressup'.  Please let me know if it works ok for you.

https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all

**Comment by Mirabellan** [comment]
As  I had to chose between either roll back to 103 in order to keep both Leatrix and CharacterStatsClassic or disable CSS in order to get Leatrix to work the choice for me was easy as Leatrix is one of the addons I really want and also want up to date.
So I just disabled CSS and now everything works as supposed.
I´ll install the alpha now as I am always looking forward to any updates on Leatrix.

Thank you for the quick reply and for an excellent work on Leatrix.

**Comment by leatrix** [comment]
As of the latest alpha, the only thing that you can't do when you have CharacterStatsClassic installed is to hide character stats by middle-clicking the character model in the character frame.  If the ability to hide character stats is not important to you, you could keep using CharacterStatsClassic if you like.  But if you want the ability to hide character stats by middle-clicking the character model, you need to remove CharacterStatsClassic.

You can download the alpha from here:
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/3299068

just click the Download button.  Or, if you have CurseForge app installed, you can click the Install button instead.

**Comment by Mirabellan** [comment]
Great, thank you. 
I didn´t get the install to work so I opted for downloading and it seems all good as usual I might add.

**Comment by leatrix** [comment]
In 1,13,105.alpha.2, middle-click to toggle character stats works with CharacterStatsClassic.
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/3299836

**Comment by Mirabellan** [comment]
Thank you, I saw both Leatrix and CharacterStatsClassic has been updated and problem is solved, good job.
