### ISSUE TITLE
Feature Request: enable automatically extending nameplate range to 41 yards

### ISSUE THREAD

**Issue by pedrorafaelpadilla** [leatrix/leatrix-plus-classic#15]

**Comment by Scrybatog** [comment]
came to +1 this reccomendation, /script SetCVar("nameplateMaxDistance", 41)

**Comment by leatrix** [comment]
In Classic, the game doesn't allow you to change the value of nameplateMaxDistance.
In BCC, you can change the value of nameplateMaxDistance and it will be saved by the game (without addons) so you only need to set it once.
