### ISSUE TITLE
Feature Request: Disable screenshake

### ISSUE THREAD

**Issue by Shakingg** [leatrix/leatrix-plus-classic#16]
Hey, screenshake is making the game unplayable for me. By googling ways to disable it I also know there are more people who can't enjoy the game because of it, albeit we are a vast minority but it's game breaking for us. So I'm hoping this is something you might be able to add to your addon, I also have to admit I know nothing about programming or making addons and have no idea if this is even possible. 

Thank you.

**Comment by leatrix** [comment]
In Shadowlands, yes, there are commands to reduce screen-shake (accessibility menu in the game options panel).  In Classic/BCC, no, the commands simply don't exist so screen-shake can't be reduced.  Best thing to do is head over to the Wow Classic forum and ask Blizzard to add the commands to Classic.
