### ISSUE TITLE
ClassicProfessionFilter SearchMats floats off CraftFrame

### ISSUE THREAD

**Issue by jpaolin** [leatrix/leatrix-plus-classic#19]
LTP version: `1.13.112.alpha.2`

SearchMats checkbox floats off the `CraftFrame` (Enchanting). Looks like the code was not copied there.
![SearchMats floats off CraftFrame](https://user-images.githubusercontent.com/5832046/123514688-33da0f80-d662-11eb-9857-37f5a027f683.png)

I'm having no issues with `TradeSkillFrame`

**Comment by leatrix** [comment]
Added to latest alpha release.

**Comment by jpaolin** [comment]
Confirmed, fixed in `1.13.112.alpha.3`. Thank you
