### ISSUE TITLE
Setting to disable keyword party invite while in queue to a battleground

### ISSUE THREAD

**Issue by 213983770** [leatrix/leatrix-plus-classic#2]
It seems that in classic if a new player joins a party while the party is queued to a battleground, the whole queue will silently reset in the background (essentially requeueing the party). This is not ideal because some guild member can unknowingly reset a queue of a group just by whispering the keyword for whatever random reason.

**Comment by leatrix** [comment]
Added to the latest alpha (at least 1.13.91.alpha.2).
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all

1.13.91.alpha.2 - 18th January 2021
- The 'Party from friends' and 'Invite from whispers' options ('Social') will no longer automatically accept or send party invitations while you are queued for a battleground.
