### ISSUE TITLE
No option to exit flight form.

### ISSUE THREAD

**Issue by olepg** [leatrix/leatrix-plus-classic#20]
Flight form is essencially a flying mount, but I'm not removed from flightform when trying to mine ores.

**Comment by leatrix** [comment]
This is the issue tracker for World of Warcraft Classic.  The issue tracker for Burning Crusade Classic is [here](https://github.com/leatrix/leatrix-plus-bcc/issues).

[Addons cannot cancel druid shapeshift forms automatically](https://wowpedia.fandom.com/wiki/API_CancelShapeshiftForm).  They can only do it through a hardware event (mouse click or keypress) which would be the same as simply unshifting manually without addons.  You could make a macro with [/cancelform](https://wowpedia.fandom.com/wiki/MACRO_cancelform) though.
