### ISSUE TITLE
Issue with muting game sounds

### ISSUE THREAD

**Issue by Alatarv** [leatrix/leatrix-plus-classic#23]
I'm running 1.13.118 in WoW Classic Era. Thanks for adding the mute game sounds. But I'm having an issue. When I attempt to silence the Fizzle sound, any time I reload the UI, I get an error. I've disabled all other addons and it still happens. It doesn't happen when the game initially loads, just when I reload the UI for some reason, but the Fizzle sound is not muted in any case. I copied the code from the pop up error box and I'll paste it below. If there's anything I should try please let me know? I LOVE the Leatrix addons! They are such a great quality of life enhancer in WoW.

Message: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:674: attempt to call global 'UnmuteSoundFile' (a nil value)
Time: Wed Sep 22 20:40:42 2021
Count: 1
Stack: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:674: attempt to call global 'UnmuteSoundFile' (a nil value)
Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:674: in function `SetupMute'
Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:681: in function `Isolated'
Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:8116: in function <Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:7754>

Locals: (for generator) = <function> defined =[C]:-1
(for state) = <table> {
 MuteInterface = <table> {
 }
 MuteFizzle = <table> {
 }
 MuteReady = <table> {
 }
 MuteTrains = <table> {
 }
}
(for control) = "MuteInterface"
k = "MuteInterface"
v = <table> {
 1 = "sound/interface/iUiInterfaceButtonA.ogg#567481"
 2 = "sound/interface/uChatScrollButton.ogg#567407"
 3 = "sound/interface/uEscapeScreenClose.ogg#567464"
 4 = "sound/interface/uEscapeScreenOpen.ogg#567490"
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "sound/interface/iUiInterfaceButtonA.ogg#567481"
 2 = "sound/interface/uChatScrollButton.ogg#567407"
 3 = "sound/interface/uEscapeScreenClose.ogg#567464"
 4 = "sound/interface/uEscapeScreenOpen.ogg#567490"
}
(for control) = 1
i = 1
e = "sound/interface/iUiInterfaceButtonA.ogg#567481"
file = "sound/interface/iUiInterfaceButtonA.ogg"
soundID = "567481"
(*temporary) = nil
(*temporary) = "567481"
(*temporary) = "attempt to call global 'UnmuteSoundFile' (a nil value)"
muteTable = <table> {
 MuteInterface = <table> {
 }
 MuteFizzle = <table> {
 }
 MuteReady = <table> {
 }
 MuteTrains = <table> {
 }
}
LeaPlusLC = <table> {
 LeaPlusNav9 = <unnamed> {
 }
 HideMiniZoomBtns = "Off"
 PlayerInCombat = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:260
 BuffFrameX = -205
 LockItem = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:81
 BuffFrameY = -13
 LeaPlusNav2.s = <unnamed> {
 }
 RecentChatSize = 170
 PlayerLogout = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:8324
 ShowMinimapIcon = "Off"
 TipCursorY = 0
 ViewPortTop = 0
 InvKey = "inv"
 NoGryphons = "Off"
 FrmEnabled = "Off"
 HideErrorMessages = "On"
 Page3 = <unnamed> {
 }
 LeaStartPage = 1
 Page0 = <unnamed> {
 }
 WidgetA = "TOP"
 WidgetScale = 1
 InviteFromWhisper = "Off"
 MinimapScale = 1
 AutoReleasePvP = "Off"
 AhBuyoutOnly = "Off"
 LeaPlusNav3.s = <unnamed> {
 }
 VanityAltLayout = "Off"
 TipHideInCombat = "Off"
 LeaPlusNav8 = <unnamed> {
 }
 LoadVarAnc = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:119
 AcceptPartyFriends = "Off"
 LockOption = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:352
 WidgetX = 0
 LeaPlusNav6.s = <unnamed> {
 }
 MakeSL = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:8544
 Page4 = <unnamed> {
 }
 NoChatFade = "Off"
 ReloadCheck = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:395
 NoRestedEmotes = "Off"
 NoPartyInvites = "Off"
 NumberOfPages = 9
 TipBackSimple = "Off"
 HideZoneText = "Off"
 CreateButton = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:8714
 EnhanceDressup = "Off"
 AutoQuestAvailable = "On"
 AutoQuestShift = "Off"
 SetDim = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:371
 HideFrames = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:268
 LeaPlusQuestFontSize = 12
 TipShowTarget = "On"
 LeaPlusNav4.s = <unnamed> {
 }
 ShowErrorsFlag = 1
 Live = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:475
 Print = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:76
 LeaPlusNav1.s = <unnamed> {
 }
 MuteTrains = "Off"
 TipOffsetX = -13
 MuteReady = "Off"
 MuteFizzle = "On"
 MuteInterface = "Off"
 ManageBuffs = "Off"
 FriendCheck = <function> defined @Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:293
 CapFirst = <function> defined @Interface\AddOns\Le

**Comment by leatrix** [comment]
Thanks for letting me know.  It was my mistake.  The 'Mute game sounds' option actually only works with game version 1.14.0 or later which is currently on the PTR.  It was included in the addon by mistake.  So I have released another update (1.13.120) with the option removed for now.  Once game version 1.14.0 is live, the option will be available again and will work fine.

**Comment by Alatarv** [comment]
Okay, thanks! Appreciate your addon. :)
