### ISSUE TITLE
Class icon portraits missing in Classic era

### ISSUE THREAD

**Issue by natbilney** [leatrix/leatrix-plus-classic#25]
Class icon portraits are currently missing in the frames options.

![image](https://user-images.githubusercontent.com/61032179/143159076-c88d28f3-01ec-4de6-ae59-efd8af4ed9e2.png)

**Comment by leatrix** [comment]
1.13.110 - 16th June 2021
- Removed the 'Class icon portraits' option ('Frames') due to performance issues.  There are standalone addons available for this feature if you need it.
