### ISSUE TITLE
default minimap & buff/debuff position off

### ISSUE THREAD

**Issue by Shoby123** [leatrix/leatrix-plus-classic#26]
Installed 1.14.10 today. I did not have any minimap or buff adjustments ticked on the prior version.

My minimap frame and buffs seemed to have been moved up, such that I couldn't see the zone text above the minimap and my buff icons were cut in half.

I reverted to the prior version and I do not have this issue.

**Comment by leatrix** [comment]
Open the 'Enhance minimap' ('Interface') configuration panel, ensure 'Unlock the minimap' is checked, hold alt and drag the minimap to where you would like it to be.  The zone text bar is now always hidden so this may have caused the minimap to be higher than it was before, but you can move it to wherever you like.

The buff frame issue will be fixed.  But for now, uncheck 'Scale entire cluster' and/or set the minimap scale to 100%.  Or, use 'Manage buffs' ('Frames') to position the buffs frame independently.

**Comment by leatrix** [comment]
This is fixed in 9.1.26 which should be available in a minute or two.  After you install it, you can move the minimap wherever you like and the buffs frame won't be affected.  If you do want to move the buffs frame though, you can use 'Manage buffs' ('Frames').  Thanks for reporting the bug.

**Comment by leatrix** [comment]
In the latest alpha, you can toggle the zone text bar once again using a setting in the configuration panel.

https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all
