### ISSUE TITLE
Enhanced minimap hides the zone name

### ISSUE THREAD

**Issue by Thex-PiedDroit** [leatrix/leatrix-plus-classic#27]
Hi there!
I really appreciate the enhanced minimap options (and the bugfix on the weird anchoring), but activating it makes the zone name disappear, which i find a little sad, and would like to have an option to have it again please.

**Comment by leatrix** [comment]
Noted.  Thank you.

**Comment by leatrix** [comment]
In the latest alpha, you can toggle the zone text bar once again using a setting in the configuration panel.

https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all

**Comment by Thex-PiedDroit** [comment]
Awesome, thank you so much!
