### ISSUE TITLE
conflict with SexyMap addon

### ISSUE THREAD

**Issue by MyTechnoHunter** [leatrix/leatrix-plus-classic#28]
using latest leatrix plus (classic) addon, if you enable the minimap tweaks sexymap no longer has the ability to resize the minimap as your addon seems to have taken precedence with the cluster zoom setting you said you disabled..

not sure what the reason for that setting is, but can you please check if sexymap is installed and sidestep that setting?

thanks in advance!

**Comment by leatrix** [comment]
If you're going to use SexyMap, you should disable 'Enhance minimap' as SexyMap offers all the same settings in its own configuration panel.  Why do you want to use both?  Pretty much all of the 'Enhance minimap' settings conflict with SexyMap so a sidestep would need to exclude everything at which point you may as well just disable 'Enhance minimap'.

**Comment by MyTechnoHunter** [comment]
ty for the info, will do!
