### ISSUE TITLE
Zone Names

### ISSUE THREAD

**Issue by dahlers1988** [leatrix/leatrix-plus-classic#29]
The latest update brought back the zone names but it's too far up; off screen. Also, "time of day" icon is still missing.

**Comment by leatrix** [comment]
You can hold alt and drag the minimap down a bit?  Now that the minimap is movable, it no longer adjusts its position when the zone text is toggled so you need to adjust it.

**Comment by dahlers1988** [comment]
Thank you! Right before checking this page, I figured that out. I did like you said. Everything good now!
