### ISSUE TITLE
Feature request: Guild rank on non-guild player

### ISSUE THREAD

**Issue by alexsmid** [leatrix/leatrix-plus-classic#3]
As i have not found any other way to request a feature:

Please add an option to see players Guild rank, outside of your own guild.
This is available in the same way the guild rank is available for players in your own guild.
I have done the following changes in Leatrix_Plus.lua:
```
if LeaPlusLC["TipShowGuild"] == "On" and LT["TipIsPlayer"] then
    local unitGuild, unitRank = GetGuildInfo(LT["Unit"])
    if unitGuild and unitRank then
        --if UnitIsInMyGuild(LT["Unit"]) then
            GameTooltip:AddLine("|c00aaaaff" .. unitGuild .. " - " .. unitRank .. "|r")
        --else
            --GameTooltip:AddLine("|c00aaaaff" .. unitGuild .. "|cffffffff|r")
        --end
    end
end
```

I have simply commented out the 3 lines above, and i now have guild ranks on all players.

**Comment by leatrix** [comment]
In 1.3.110.alpha.4, there's a new setting that let's you see ranks for players in other guilds. It's disabled by default. This setting is also in the latest alpha releases for Burning Crusade Classic and Shadowlands.
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all
https://github.com/leatrix/leatrix-plus-bcc/issues/23
