### ISSUE TITLE
square map icon placement issue

### ISSUE THREAD

**Issue by knasen88** [leatrix/leatrix-plus-classic#31]
Always been a fan of square map so huge thanks for adding that, however now the Track minerals (or any other type i suppose) overlaps with mail icon and the battleground icon overlaps with the displayed time

![image](https://user-images.githubusercontent.com/16074363/145366583-8c57dd10-fc6d-4169-9422-c32450e990c9.png)

**Comment by leatrix** [comment]
Please try 1.14.14.alpha.1 (or later) and let me know how you go on.
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all
