### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by paroyer** [leatrix/leatrix-plus-classic#4]
1x Leatrix_Plus\Leatrix_Plus-1.13.95.lua:4863: Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string
[C]: ?
Ace3\AceHook-3.0\AceHook-3.0-9.lua:130: in function <Ace3\AceHook-3.0\AceHook-3.0.lua:118>
Ace3\AceHook-3.0\AceHook-3.0-9.lua:367: in function `HookScript'
Leatrix_Plus\Leatrix_Plus-1.13.95.lua:4863: in function `HighlightTabs'
Leatrix_Plus\Leatrix_Plus-1.13.95.lua:4880: in function `Player'
Leatrix_Plus\Leatrix_Plus-1.13.95.lua:7693: in function <Leatrix_Plus\Leatrix_Plus.lua:7326>

Locals:
(*temporary) = "Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string"

**Comment by leatrix** [comment]
This is caused by 'Hide chat buttons' ('Chat').  Are you using a chat addon?  Disable other addons.  Does that fix the problem?  Enable other addons gradually until you find the addon causing the problem.

**Comment by paroyer** [comment]
Ohh yeah that's probably it, I had an addon to hide chat button but I'm using leatrix now 9/10 I forgot deleting the other one -_-
