### ISSUE TITLE
Windowed/fullscreen toggle disapeared

### ISSUE THREAD

**Issue by rsepierre** [leatrix/leatrix-plus-classic#44]
I can't seem to find what I remember as one of the main feature or Leatrix Plus that I was using basically anytime It would be useful to have WoW taking only half the screen. I would hit `ctrl+alt+click` on leatrix (windowed mode toggle) then `win + left arrow` (resize window to half of screen). Nice and easy

The most astonishing to me isn't necessarely that it dissapeared. It could have been an API update preventing leatrix from changing window mode or viewed as an unecessary feature even though it was for me. The most astonishing to me is that it is very hard to find any reference to that feature online "windowed leatrix"

Also the only reference of it found on this is the patch note of [1.14.64](https://github.com/leatrix/leatrix-plus-classic/blob/74c6899c9af0ecadd0f6b95ab578fb676041c7cc/CHANGELOG.txt) which is actually fairly recent and mentions an update on the function. But for me it's been a couple of month for me that it simply disapeared.

This is what I see when I hover leatrix. No mention of the feature that used to be there.
![image](https://user-images.githubusercontent.com/6746875/213905214-31873cfd-b2a7-412a-a7a5-a5cb47edbbb8.png)

**Comment by leatrix** [comment]
It seems to work fine for me.  The minimap button tooltip has never showed the modifier key and click combinations.  They are shown in the 'Show minimap button' ('Settings') option tooltip.

![image](https://user-images.githubusercontent.com/58888415/213909156-99949120-bd93-4b1e-bf50-ddd60c965263.png)

While the game window is windowed, the Windows shortcut keys you mentioned work fine too but, of course, they are controlled by Windows and not the addon.

**Comment by rsepierre** [comment]
You are 100% correct.
I couldn't find that tooltip and somehow my brain flipped to ctrl + alt + right clicking and not being able to find the tooltip. 
I convinced myself it got removed.
Sorry for this
