### ISSUE TITLE
Feature Request: smaller chat font sizes

### ISSUE THREAD

**Issue by Hr46ph** [leatrix/leatrix-plus-classic#6]
Short of installing yet another large, bloated addon which adds more redundant features with Leatrix or other addons I already use, I cannot find a simple, lightweight addon to change the chat font size to something smaller.

It would be really useful if Leatrix Plus for Classic could do this.

Hope you will consider.
Thanks!

**Comment by leatrix** [comment]
Suggestion appreciated.
