### ISSUE TITLE
Feature request: Automatically enable find minerals/herbs

### ISSUE THREAD

**Issue by Limero** [leatrix/leatrix-plus-classic#7]
I use an addon called "Giga Auto Resources Tracker" that is a simple addon that automatically enable "Find Minerals" or "Find Herbs" after you resurrect from death. It would be great if this option was available directly in Leatrix Plus, instead of requiring a separate addon.

Link to Giga Auto Resources Tracker:
https://www.curseforge.com/wow/addons/gigaautoresourcestracker

**Comment by leatrix** [comment]
Feedback appreciated.
